version: '3'
services:
  mysql:
    image: mysql:8
    container_name: fullbazel_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: fullbazel_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:6.1.0
    container_name: fullbazel_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    depends_on:
      - zookeeper

  server:
    image: node:lts
    container_name: fullbazel_server
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./node_modules:/node_modules
      - ./libs:/libs
      - ./nodejs-server:/nodejs-server
    ports:
      - '3000:3000'
    env_file: libs/config/dev.config
    command: yarn run ts-node-dev -r tsconfig-paths/register --project nodejs-server/tsconfig.json nodejs-server dev
    depends_on:
      - mysql
      - kafka
