export enum Tags {
  Angular = 'angular',
  Bazel = 'bazel',
  Typescript = 'typescript',
  ServerSideRendering = 'server-side-rendering',
  ProgressiveWebApp = 'progressive-web-app',
  ServiceWorker = 'service-worker',
  LazyLoading = 'lazy-loading',
  NodeJs = 'node.js',
  Sass = 'sass',
  HTML = 'html',
  Monorepo = 'monorepo',
  WebSockets = 'web-sockets',
  NgRx = 'ngrx',
}
