apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-client
spec:
  selector:
    matchLabels:
      app: nextjs-client
  replicas: 2
  template:
    metadata:
      labels:
        app: nextjs-client
    spec:
      containers:
        - name: nextjs-client
          image: gcr.io/fullstack-bazel-306720/nextjs-client:latest
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
            limits:
              memory: 1000Mi
              cpu: 500m
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-client
spec:
  selector:
    app: nextjs-client
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nextjs-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: nextjs-client
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
