steps:
  - name: node
    entrypoint: yarn
    args: ["install", "--ignore-engines"]

  - name: eu.gcr.io/fullstack-bazel/cloudbuild
    args: ['build', '--google_default_credentials', '--remote_http_cache=https://storage.googleapis.com/abs-bazel-cache', '//...']

  - name: eu.gcr.io/fullstack-bazel/cloudbuild
    args: ['test', '--google_default_credentials', '--remote_http_cache=https://storage.googleapis.com/abs-bazel-cache', '//...']

timeout: 3600s